services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    environment:
      PB_ADMIN_EMAIL: admin@example.com
      PB_ADMIN_PASSWORD: password123
    ports:
      - "8090:8090"
    volumes:
      - ./database/pb_data:/pb_data
      - ./database/pb_migrations:/pb_migrations
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
