services:
  homeserver:
    # Bypasses Docker Hub entirely!
    image: forgejo.ellis.link/continuwuation/continuwuity:latest
    ports:
      - "8008:6167"
    environment:
      CONTINUWUITY_SERVER_NAME: "localhost"
      CONTINUWUITY_ALLOW_REGISTRATION: "true"
      CONTINUWUITY_DATABASE_BACKEND: "rocksdb"
      CONTINUWUITY_DATABASE_PATH: "/var/lib/matrix-conduit/"
      CONTINUWUITY_LOG: "warn"
      CONTINUWUITY_ADDRESS: "0.0.0.0"
      CONTINUWUITY_PORT: "6167"
