allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - coralite-scripts@0.43.2 || 0.43.3 || 0.43.4 || 0.43.5 || 0.43.6 || 0.44.0 || 0.44.1 || 0.44.2 || 0.45.0 || 0.45.1 || 0.46.0
  - coralite@0.43.2 || 0.43.3 || 0.43.4 || 0.43.5 || 0.43.6 || 0.44.0 || 0.44.1 || 0.44.2 || 0.45.0 || 0.45.1 || 0.46.0
