allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - coralite-scripts@0.43.2 || 0.43.3 || 0.43.4 || 0.43.5 || 0.43.6 || 0.44.0
  - coralite@0.43.2 || 0.43.3 || 0.43.4 || 0.43.5 || 0.43.6 || 0.44.0
