export default [
  {
    name: 'unit-smoke',
    type: 'unit',
    runner: 'node',
    description: 'Smoke tests that prove the test runner is operational.',
    files: [
      'tests/unit/smoke.test.js',
      'tests/unit/oprf.test.js',
      'tests/unit/api.test.js',
      'tests/unit/codec.test.js',
      'tests/unit/auth-opaque.test.js',
      'tests/unit/auth-session.test.js',
      'tests/unit/auth-login-flow.test.js',
      'tests/unit/css-bundle.test.js',
      'tests/unit/crypto-display-name.test.js',
      'tests/unit/auth-identity.test.js',
      'tests/unit/auth-register-flow.test.js',
      'tests/unit/auth-boot.test.js',
      'tests/unit/i18n.test.js',
      'tests/unit/i18n-locales.test.js',
      'tests/unit/i18n-plugin.test.js',
      'tests/unit/icons.test.js',
      'tests/unit/components-defineComponent.test.js',
      'tests/unit/components-data-attrs.test.js',
      'tests/unit/auth-recover-flow.test.js',
      'tests/unit/auth-revocation.test.js',
      'tests/unit/shell.test.js',
      'tests/unit/extend-define-extension.test.js',
      'tests/unit/extend-registry.test.js',
      'tests/unit/extend-ctx.test.js',
      'tests/unit/extend-plugin.test.js',
      'tests/unit/extend-validate.test.js',
      'tests/unit/extend-validate-link.test.js',
      'tests/unit/extend-vocab.test.js',
      'tests/unit/extend-vocab-cli.test.js',
      'tests/unit/extend-first-party.test.js',
      'tests/unit/router.test.js',
      'tests/unit/surface-reconcile.test.js',
      'tests/unit/db.test.js',
      'tests/unit/wasm-backend.test.js',
      'tests/unit/storage-plugin.test.js',
      'tests/unit/storage-plugin-config.test.js',
      'tests/unit/state.test.js',
      'tests/unit/repositories-users.test.js',
      'tests/unit/repositories-rooms.test.js',
      'tests/unit/repositories-room-members.test.js',
      'tests/unit/repositories-room-order.test.js',
      'tests/unit/repositories-messages.test.js',
      'tests/unit/repositories-attachments.test.js',
      'tests/unit/repositories-reactions.test.js',
      'tests/unit/repositories-read-state.test.js',
      'tests/unit/repositories-drafts.test.js',
      'tests/unit/repositories-blocked-users.test.js',
      'tests/unit/repositories-outbox.test.js',
      'tests/unit/repositories-room-preferences.test.js',
      'tests/unit/repositories-nicknames.test.js',
      'tests/unit/repositories-device-names.test.js',
      'tests/unit/repositories-starred-items.test.js',
      'tests/unit/repositories-sync-state.test.js',
      'tests/unit/repositories-processed-events.test.js',
      'tests/unit/repositories-mls-rooms.test.js',
      'tests/unit/sync.test.js',
      'tests/unit/sync-plugin.test.js',
      'tests/unit/view-chats-data.test.js',
      'tests/unit/view-chat-data.test.js',
      'tests/unit/composer.test.js',
      'tests/unit/send-message.test.js',
      'tests/unit/message-actions.test.js',
      'tests/unit/edit-message.test.js'
    ]
  },
  {
    name: 'component-smoke',
    type: 'component',
    runner: 'playwright',
    description: 'Smoke tests for component rendering and Playwright pipeline.',
    files: [
      'tests/component/smoke.spec.js',
      'tests/component/tokens.spec.js',
      'tests/component/css-applied.spec.js',
      'tests/component/hydration.spec.js',
      'tests/component/shell.spec.js',
      'tests/component/rail.spec.js',
      'tests/component/surface.spec.js',
      'tests/component/ui-icon.spec.js',
      'tests/component/conversation-list.spec.js',
      'tests/component/chat-thread.spec.js',
      'tests/component/composer.spec.js',
      'tests/component/message-context-menu.spec.js',
      'tests/component/message-edit.spec.js',
      'tests/component/ui-sheet.spec.js'
    ]
  },
  {
    name: 'component-auth',
    type: 'component',
    runner: 'playwright',
    description: 'Component tests for authentication gate, login, and registration forms.',
    files: [
      'tests/component/auth-gate.spec.js',
      'tests/component/auth-login-flow.spec.js',
      'tests/component/register-form.spec.js',
      'tests/component/messenger-boot.spec.js',
      'tests/component/auth-recovery.spec.js',
      'tests/component/sync.spec.js'
    ]
  },
  {
    name: 'component-i18n',
    type: 'component',
    runner: 'playwright',
    description: 'Component tests for i18n locale rendering and migration verification.',
    files: [
      'tests/component/i18n-migration.spec.js'
    ]
  }
]
