-- Coralite Server V2 Consolidated Schema
-- Generated by MIG-RESET from V-G's target schema.
-- See verification/mig-consolidation-readiness/report.md §9.

-- Core Identity & Users
CREATE TABLE IF NOT EXISTS users (
    id                      TEXT PRIMARY KEY,
    -- username_token: stores lookup_token, not the raw OPRF finalization output.
    -- 86-character unpadded base64url, decodes to 64 bytes. See §6.19.
    username_token          TEXT NOT NULL UNIQUE,
    -- encrypted_display: nonce (12) || AES-256-GCM(display_name). 28–284 bytes decoded.
    encrypted_display       TEXT,
    opaque_registration     BLOB NOT NULL,
    identity_pubkey         TEXT NOT NULL,
    profile                 TEXT,
    profile_version         INTEGER NOT NULL DEFAULT 1,
    max_file_size_bytes     INTEGER,
    created_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    disabled_at             DATETIME,
    deleted_at              DATETIME,
    requires_reregistration INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_token ON users(username_token);

CREATE TABLE IF NOT EXISTS user_seq (
    user_id     TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    next_seq    INTEGER NOT NULL DEFAULT 1
);

-- Access Control & Roles
CREATE TABLE IF NOT EXISTS roles (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    level       INTEGER NOT NULL,
    permissions TEXT NOT NULL
);

INSERT OR IGNORE INTO roles (id, name, level, permissions) VALUES
    ('role_owner',   'owner',   100, '["*"]'),
    ('role_admin',   'admin',    80, '["user.manage","invite.unlimited","config.edit","room.force_delete","backup.manage"]'),
    ('role_inviter', 'inviter',  50, '["invite.limited"]'),
    ('role_member',  'member',   10, '["room.create","room.join","message.send"]');

CREATE TABLE IF NOT EXISTS user_roles (
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id    TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by TEXT REFERENCES users(id),
    PRIMARY KEY (user_id, role_id)
);

-- Devices & Sessions
CREATE TABLE IF NOT EXISTS devices (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id   TEXT NOT NULL UNIQUE,
    platform    TEXT NOT NULL CHECK(platform IN ('web', 'ios', 'android', 'desktop')),
    last_seen   DATETIME,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_devices_user ON devices(user_id);

CREATE TABLE IF NOT EXISTS device_names (
    user_id               TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id             TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    encrypted_device_name TEXT NOT NULL,
    user_seq              INTEGER NOT NULL,
    updated_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at            DATETIME,
    PRIMARY KEY (user_id, device_id)
);
CREATE INDEX IF NOT EXISTS idx_device_names_seq ON device_names(user_id, user_seq);

CREATE TABLE IF NOT EXISTS sessions (
    id           TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id    TEXT REFERENCES devices(id) ON DELETE CASCADE,
    token_hash   TEXT NOT NULL UNIQUE,
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at   DATETIME NOT NULL,
    revoked_at   DATETIME,
    last_seen_at DATETIME
);
CREATE INDEX IF NOT EXISTS idx_sessions_user_active
    ON sessions(user_id, expires_at)
    WHERE revoked_at IS NULL;

-- Invites
CREATE TABLE IF NOT EXISTS server_invites (
    id           TEXT PRIMARY KEY,
    code         TEXT NOT NULL UNIQUE,
    created_by   TEXT REFERENCES users(id),
    max_uses     INTEGER NOT NULL,
    current_uses INTEGER NOT NULL DEFAULT 0,
    expires_at   DATETIME,
    revoked_at   DATETIME,
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_server_invites_code
    ON server_invites(code)
    WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_server_invites_created_by
    ON server_invites(created_by, created_at DESC);

-- Rooms & Membership
CREATE TABLE IF NOT EXISTS rooms (
    id                  TEXT PRIMARY KEY,
    owner_id            TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    retention_days      INTEGER,
    max_file_size_bytes INTEGER,
    moderation_override TEXT,
    metadata            TEXT,
    metadata_version    INTEGER NOT NULL DEFAULT 1,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_rooms_owner ON rooms(owner_id);

CREATE TABLE IF NOT EXISTS room_members (
    room_id    TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       TEXT NOT NULL DEFAULT 'member',
    joined_via TEXT,
    joined_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (room_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_room_members_user ON room_members(user_id, joined_at DESC);
CREATE INDEX IF NOT EXISTS idx_room_members_room_role ON room_members(room_id, role);

CREATE TABLE IF NOT EXISTS room_invites (
    id           TEXT PRIMARY KEY,
    room_id      TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    code         TEXT NOT NULL UNIQUE,
    created_by   TEXT NOT NULL REFERENCES users(id),
    max_uses     INTEGER NOT NULL,
    current_uses INTEGER NOT NULL DEFAULT 0,
    expires_at   DATETIME,
    revoked_at   DATETIME,
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_room_invites_room_active ON room_invites(room_id, created_at DESC) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_room_invites_code ON room_invites(code);

CREATE TABLE IF NOT EXISTS room_epochs (
    room_id                   TEXT PRIMARY KEY REFERENCES rooms(id) ON DELETE CASCADE,
    epoch                     INTEGER NOT NULL DEFAULT 0,
    sequence                  INTEGER NOT NULL DEFAULT 0,
    confirmed_transcript_hash BLOB,
    created_at                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Messaging & Reactions
CREATE TABLE IF NOT EXISTS room_messages (
    id               TEXT PRIMARY KEY,
    room_id          TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    sender_user_id   TEXT NOT NULL REFERENCES users(id),
    sender_client_id TEXT NOT NULL,
    epoch            INTEGER NOT NULL,
    seq              INTEGER NOT NULL,
    content_type     TEXT NOT NULL CHECK(content_type IN ('application', 'commit', 'proposal', 'bot')),
    ciphertext       BLOB NOT NULL,
    reply_to         TEXT REFERENCES room_messages(id),
    target_user_ids  TEXT,
    edit_of          TEXT REFERENCES room_messages(id),
    edit_sequence    INTEGER NOT NULL DEFAULT 0,
    edited_at        DATETIME,
    deleted_at       DATETIME,
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_room_messages_room_epoch_seq ON room_messages(room_id, epoch, seq);
CREATE INDEX IF NOT EXISTS idx_room_messages_room_created ON room_messages(room_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_room_messages_sender ON room_messages(sender_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_room_messages_room_deleted ON room_messages(room_id, deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_room_messages_edit_of ON room_messages(edit_of) WHERE edit_of IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_room_messages_reply_to ON room_messages(reply_to) WHERE reply_to IS NOT NULL;

CREATE TABLE IF NOT EXISTS reactions (
    id               TEXT PRIMARY KEY,
    room_id          TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    message_id       TEXT NOT NULL REFERENCES room_messages(id) ON DELETE CASCADE,
    sender_user_id   TEXT NOT NULL REFERENCES users(id),
    sender_client_id TEXT NOT NULL,
    reaction         TEXT NOT NULL,
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at       DATETIME,
    UNIQUE (message_id, sender_user_id, sender_client_id, reaction)
);
CREATE INDEX IF NOT EXISTS idx_reactions_message ON reactions(message_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_reactions_room ON reactions(room_id, created_at DESC);

-- MLS Coordination
CREATE TABLE IF NOT EXISTS key_packages (
    id             TEXT PRIMARY KEY,
    user_id        TEXT REFERENCES users(id) ON DELETE CASCADE,
    bot_id         TEXT REFERENCES bot_accounts(id) ON DELETE CASCADE,
    client_id      TEXT NOT NULL,
    cipher_suite   INTEGER NOT NULL DEFAULT 1,
    key_package    BLOB NOT NULL,
    init_key_hash  BLOB,
    is_last_resort INTEGER NOT NULL DEFAULT 0,
    consumed       INTEGER NOT NULL DEFAULT 0,
    consumed_at    DATETIME,
    created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (user_id IS NOT NULL AND bot_id IS NULL)
        OR
        (user_id IS NULL AND bot_id IS NOT NULL)
    )
);
CREATE INDEX IF NOT EXISTS idx_kp_claim_order ON key_packages(user_id, consumed, is_last_resort, created_at ASC, id ASC) WHERE consumed = 0;
CREATE INDEX IF NOT EXISTS idx_key_packages_bot_active
    ON key_packages(bot_id, client_id, consumed)
    WHERE consumed = 0 AND bot_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS welcomes (
    id                  TEXT PRIMARY KEY,
    room_id             TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    recipient_user_id   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_client_id TEXT NOT NULL,
    welcome_data        BLOB NOT NULL,
    consumed            INTEGER NOT NULL DEFAULT 0,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_welcomes_recipient ON welcomes(recipient_user_id, consumed, created_at DESC);

CREATE TABLE IF NOT EXISTS pending_mls_removes (
    id               TEXT PRIMARY KEY,
    room_id          TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    target_user_id   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_client_id TEXT NOT NULL,
    queued_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    consumed_at      DATETIME
);
CREATE INDEX IF NOT EXISTS idx_pending_mls_removes_pending ON pending_mls_removes(room_id, queued_at ASC) WHERE consumed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_pending_mls_removes_active ON pending_mls_removes(room_id, consumed_at) WHERE consumed_at IS NULL;

CREATE TABLE IF NOT EXISTS pending_mls_adds (
    id               TEXT PRIMARY KEY,
    room_id          TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    target_user_id   TEXT REFERENCES users(id),
    target_bot_id    TEXT REFERENCES bot_accounts(id),
    target_client_id TEXT NOT NULL,
    key_package_id   TEXT NOT NULL REFERENCES key_packages(id),
    queued_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    consumed_at      DATETIME,
    CHECK (
        (target_user_id IS NOT NULL AND target_bot_id IS NULL)
        OR
        (target_user_id IS NULL AND target_bot_id IS NOT NULL)
    )
);
CREATE INDEX IF NOT EXISTS idx_pending_mls_adds_active ON pending_mls_adds(room_id, consumed_at) WHERE consumed_at IS NULL;

-- Attachments
CREATE TABLE IF NOT EXISTS attachments (
    id                 TEXT PRIMARY KEY,
    room_id            TEXT REFERENCES rooms(id) ON DELETE CASCADE,
    uploader_id        TEXT NOT NULL REFERENCES users(id),
    uploader_client_id TEXT,
    storage_backend    TEXT NOT NULL CHECK(storage_backend IN ('fs', 's3')),
    storage_key        TEXT NOT NULL,
    padded_size        INTEGER NOT NULL,
    plaintext_size     INTEGER NOT NULL,
    encrypted_size     INTEGER NOT NULL,
    chunk_size         INTEGER NOT NULL,
    chunk_count        INTEGER NOT NULL,
    nonce_prefix       TEXT NOT NULL,
    base_counter       INTEGER NOT NULL,
    content_type       TEXT NOT NULL DEFAULT 'application/octet-stream',
    created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_attachments_room_created ON attachments(room_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attachments_uploader_created ON attachments(uploader_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attachments_created ON attachments(created_at);

-- User Sync & State
CREATE TABLE IF NOT EXISTS read_state (
    user_id              TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    room_id              TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    last_read_message_id TEXT,
    user_seq             INTEGER NOT NULL,
    updated_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at           DATETIME,
    PRIMARY KEY (user_id, room_id)
);
CREATE INDEX IF NOT EXISTS idx_read_state_seq ON read_state(user_id, user_seq);

CREATE TABLE IF NOT EXISTS user_preferences (
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key        TEXT NOT NULL,
    value_json TEXT NOT NULL,
    user_seq   INTEGER NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, key)
);
CREATE INDEX IF NOT EXISTS idx_user_preferences_seq ON user_preferences(user_id, user_seq);

CREATE TABLE IF NOT EXISTS starred_items (
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_id    TEXT NOT NULL,
    item_type  TEXT NOT NULL,
    room_id    TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    user_seq   INTEGER NOT NULL,
    starred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    PRIMARY KEY (user_id, item_id, item_type)
);
CREATE INDEX IF NOT EXISTS idx_starred_items_seq ON starred_items(user_id, user_seq);
CREATE INDEX IF NOT EXISTS idx_starred_items_room ON starred_items(user_id, room_id, starred_at DESC);

-- Account Recovery
CREATE TABLE IF NOT EXISTS recovery_codes (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_hash   BLOB NOT NULL,
    code_salt   BLOB NOT NULL,
    consumed_at DATETIME,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_recovery_codes_user ON recovery_codes(user_id, consumed_at) WHERE consumed_at IS NULL;

-- Key Transparency
CREATE TABLE IF NOT EXISTS key_transparency_log (
    leaf_index      INTEGER PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    username_token  TEXT NOT NULL,
    identity_pubkey TEXT NOT NULL,
    added_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_kt_user ON key_transparency_log(user_id);
CREATE INDEX IF NOT EXISTS idx_kt_added ON key_transparency_log(added_at);

CREATE TABLE IF NOT EXISTS key_transparency_snapshots (
    id         TEXT PRIMARY KEY,
    tree_size  INTEGER NOT NULL,
    root_hash  BLOB NOT NULL,
    signature  BLOB,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Calls
CREATE TABLE IF NOT EXISTS call_sessions (
    id           TEXT PRIMARY KEY,
    room_id      TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    initiator_id TEXT NOT NULL REFERENCES users(id),
    started_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at     DATETIME
);
CREATE INDEX IF NOT EXISTS idx_call_sessions_room ON call_sessions(room_id, started_at DESC);

CREATE TABLE IF NOT EXISTS call_participants (
    call_id   TEXT NOT NULL REFERENCES call_sessions(id) ON DELETE CASCADE,
    user_id   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at   DATETIME,
    PRIMARY KEY (call_id, user_id)
);

-- Room Sessions
CREATE TABLE IF NOT EXISTS room_sessions (
    id               TEXT PRIMARY KEY,
    room_id          TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    extension_id     TEXT NOT NULL,
    session_type     TEXT NOT NULL,
    metadata         TEXT,
    metadata_version INTEGER NOT NULL DEFAULT 1,
    position         INTEGER NOT NULL,
    created_by       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_room_sessions_room_pos ON room_sessions(room_id, position ASC);
CREATE INDEX IF NOT EXISTS idx_room_sessions_created_by ON room_sessions(created_by);

-- Push Subscriptions
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id           TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id    TEXT REFERENCES devices(id) ON DELETE CASCADE,
    platform     TEXT NOT NULL,
    endpoint     TEXT,
    p256dh       TEXT,
    auth         TEXT,
    push_token   TEXT,
    browser_id   TEXT,
    user_agent   TEXT,
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at DATETIME,
    revoked_at   DATETIME
);

-- Instance Config & Limits
CREATE TABLE IF NOT EXISTS instance_config (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS instance_limits (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT REFERENCES users(id)
);

-- Audit Logging & Rate Limits
CREATE TABLE IF NOT EXISTS audit_log (
    id          TEXT PRIMARY KEY,
    actor_id    TEXT REFERENCES users(id),
    action      TEXT NOT NULL,
    target_type TEXT,
    target_id   TEXT,
    metadata    TEXT,
    ip_address  TEXT,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_actor_created ON audit_log(actor_id, created_at DESC) WHERE actor_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_audit_action_created ON audit_log(action, created_at DESC);

CREATE TABLE IF NOT EXISTS rate_limits (
    key          TEXT NOT NULL,
    window_start INTEGER NOT NULL,
    count        INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (key, window_start)
);
CREATE INDEX IF NOT EXISTS idx_rate_limits_window ON rate_limits(window_start);

CREATE TABLE IF NOT EXISTS oprf_audit (
    id         TEXT PRIMARY KEY,
    event      TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_oprf_audit_created ON oprf_audit(created_at DESC);

-- Minimal Bot Tables for Member Pagination Merge
CREATE TABLE IF NOT EXISTS bot_accounts (
    id                  TEXT PRIMARY KEY,
    display_name        TEXT NOT NULL,
    avatar_file_id      TEXT,
    owner_user_id       TEXT NOT NULL REFERENCES users(id),
    disabled_at         DATETIME,
    deleted_at          DATETIME
);

CREATE TABLE IF NOT EXISTS room_bots (
    room_id    TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    bot_id     TEXT NOT NULL REFERENCES bot_accounts(id) ON DELETE CASCADE,
    mode       TEXT NOT NULL CHECK(mode IN ('write_only', 'observer', 'member')),
    granted_by TEXT NOT NULL REFERENCES users(id),
    granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at DATETIME,
    PRIMARY KEY (room_id, bot_id)
);

CREATE INDEX IF NOT EXISTS idx_room_bots_active
    ON room_bots(room_id, bot_id)
    WHERE revoked_at IS NULL;
